
require("core.settings")
require("core.keybinds")
require("core.plugins")
require("core.plugin_config.lsp.mason")
require("core.plugin_config.lsp.lsp_config")
require("core.plugin_config.treesitter")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.cmp")
require("core.plugin_config.lualine")
